### ISSUE TITLE
mvls: failed discovering any devices: No error information

### ISSUE THREAD

**Issue by robimarko** [wkz/mdio-tools#13]
Hi,

First of all, thanks for the hard work on the tool, it has really helped me the last few months.

I am working on MikroTik RB5009 support for OpenWrt under 5.15, the mdio tool has proved extremely useful so far
with the MV88E6393X switch, it uses.
I just saw today that you have an mvls tool that is Link Street specific for providing various access to the switch using devlink.
This is something that would be really useful for me, so I tried using it, first of all, OpenWrt doesn't package it but that was easy to fix as well as updating the kernel module and userspace to 1.0.1 release(I have a PR for that).
But then I tried using it, but it failed with:
```
root@OpenWrt:/# mvls 
mvls: failed discovering any devices: No error information
```

I looked and the devlink part looks to be exposed just fine:
```
root@OpenWrt:/# devlink dev
mdio_bus/f212a200.mdio-mii:00
root@OpenWrt:/# devlink region
mdio_bus/f212a200.mdio-mii:00/global1: size 64 snapshot []
mdio_bus/f212a200.mdio-mii:00/global2: size 64 snapshot []
mdio_bus/f212a200.mdio-mii:00/atu: size 49152 snapshot []
mdio_bus/f212a200.mdio-mii:00/vtu: size 131072 snapshot []
mdio_bus/f212a200.mdio-mii:00/pvt: size 1024 snapshot []
mdio_bus/f212a200.mdio-mii:00/port: size 64 snapshot []
mdio_bus/f212a200.mdio-mii:00/port: size 64 snapshot []
mdio_bus/f212a200.mdio-mii:00/port: size 64 snapshot []
mdio_bus/f212a200.mdio-mii:00/port: size 64 snapshot []
mdio_bus/f212a200.mdio-mii:00/port: size 64 snapshot []
mdio_bus/f212a200.mdio-mii:00/port: size 64 snapshot []
mdio_bus/f212a200.mdio-mii:00/port: size 64 snapshot []
mdio_bus/f212a200.mdio-mii:00/port: size 64 snapshot []
mdio_bus/f212a200.mdio-mii:00/port: size 64 snapshot []
mdio_bus/f212a200.mdio-mii:00/port: size 64 snapshot []
mdio_bus/f212a200.mdio-mii:00/port: size 64 snapshot []
```

The switch uses single-chip adressing.

Do you maybe have some ideas?

Regards,
Robert

**Comment by wkz** [comment]
Good to hear!

Hopefully, it is just because I haven't mapped the Amethyst IDs in the tool. Could you try building from master (004fcd9) and see if that works?

**Comment by robimarko** [comment]
Thanks, it works with that commit.

Regards,
Robert
