### ISSUE TITLE
sys/queue.h is used even when unavailable

### ISSUE THREAD

**Issue by neheb** [wkz/mdio-tools#19]
musl libc does not come with sys/queue.h by default, breaking compilation.

Potential fallback is libbsd, preferably the overlay mode.

**Comment by troglobit** [comment]
I suggest importing the latest queue.h from OpenBSD and using that instead, it carries the _SAFE macros as well which are preferable when traversing lists while deleting nodes.  No need to add another external dependency (libbsd) to this project for this.

**Comment by robimarko** [comment]
@neheb On what host is this breaking?

Works fine for me

**Comment by neheb** [comment]
OpenWrt with the sys/queue.h header removed. The goal is to reduce OpenWrt's diff compared to upstream. Removing sys/queue.h seems to be too hard as projects seem unwilling to use libbsd.

**Comment by robimarko** [comment]
That is gonna be hard as nobody wants additional dependency
