### ISSUE TITLE
Issues linking with relocations in a read-only section on Fedora 40

### ISSUE THREAD

**Issue by nullr0ute** [wkz/mdio-tools#37]
When building on Fedora, with it's various compiler flags for security, the linker complains about relocations in a read-only section:

`gcc -Wall -Wextra -Werror -Wno-unused-parameter -I ../../include  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer   -Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes  -o mdio mdio-bus.o mdio-main.o mdio-mdio.o mdio-mva.o mdio-mvls.o mdio-phy.o mdio-print_phy.o mdio-xrs.o -lmnl 
/usr/bin/ld: /tmp/ccyflkye.ltrans0.ltrans.o: warning: relocation against `__stop_cmds' in read-only section `.text.startup'
/usr/bin/ld: /tmp/ccyflkye.ltrans0.ltrans.o: in function `main':
/home/perobins/rpmbuild/BUILD/mdio-tools-1.3.1/src/mdio/main.c:170:(.text.startup+0x14a): undefined reference to `__stop_cmds'
/usr/bin/ld: /home/perobins/rpmbuild/BUILD/mdio-tools-1.3.1/src/mdio/main.c:170:(.text.startup+0x151): undefined reference to `__start_cmds'
/usr/bin/ld: warning: creating DT_TEXTREL in a PIE
`

**Comment by wkz** [comment]
Is there an option to get a plain GCC to emit this warning/error?

I see lots of references to Red Hat specific spec files, so I'm just wondering how to reproduce it on my system. If you could provide the minimum extra `{C,CPP,LD}FLAGS` needed, that would be great!

**Comment by MattCatz** [comment]
I've also run into this issue. It seems to be the compiler trying to shed 'unused' symbols. I'm not 100% certain but the `extern` structs here are never defined anywhere else so the compiler probably thinks it doesn't need them.

Regardless, this command should recreate the issue locally: `CFLAGS="$CFLAGS -flto -Og" ./configure && make`

**Comment by wkz** [comment]
Fixed in #38

**Comment by nullr0ute** [comment]
thanks folks!
